{
 "title": "Cloudflare ZeroTrust Organization",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    { "expr": "zerotrust_users_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Gateway",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Seats" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "zerotrust_users_up{gateway_seat=\"true\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Access",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Seats" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "zerotrust_users_up{access_seat=\"true\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Devices",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    { "expr": "zerotrust_devices_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "OS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Linux" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "zerotrust_devices_up{platform=\"linux\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Windows" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "zerotrust_devices_up{platform=\"windows\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tunnels",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    { "expr": "zerotrust_tunnels_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "UP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Online" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    { "expr": "zerotrust_tunnels_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "DOWN",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Offline" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    { "expr": "zerotrust_tunnels_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "DEX Tests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    { "expr": "zerotrust_dex_test_1h_avg_ms", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Traceroute",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "zerotrust_dex_test_1h_avg_ms{kind=\"traceroute\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "zerotrust_dex_test_1h_avg_ms{kind=\"http\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Users Status",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "zerotrust_users_up", "legendFormat": "{{user_email}}" }
   ]
  },
  {
   "title": "Devices",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "zerotrust_devices_up", "legendFormat": "{{device_name}}" }
   ]
  },
  {
   "title": "Tunnels",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "zerotrust_tunnels_up", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Dex Tests",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "zerotrust_dex_test_1h_avg_ms", "legendFormat": "{{test_name}}" }
   ]
  },
  {
   "title": "Users Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "count(zerotrust_users_up)", "legendFormat": "{{user_email}}" }
   ]
  },
  {
   "title": "Devices Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(zerotrust_devices_status)",
     "legendFormat": "{{user_email}}"
    }
   ]
  },
  {
   "title": "# of Hops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "hops" } },
   "targets": [
    { "expr": "zerotrust_traceroute_hops", "legendFormat": "{{test_name}}" }
   ]
  },
  {
   "title": "RTT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "zerotrust_traceroute_rtt", "legendFormat": "{{test_name}}" }
   ]
  }
 ]
}